---
description: "Update a config group (resource: PUT /api/config_groups/:id)"
enabled: true
runner_type: "python-script"
entry_point: lib/action.py
name: config_groups.update
pack: foreman
parameters:
  operation:
    type: string
    default: config_groups.update
    immutable: true
  connection:
    type: string
    description: "Name of <connection> from this pack's configuration that specifies how to connect to a server."
    required: false
  server:
    type: string
    description: "Optional override of the server in <connection> (required if <connection> is not specified)."
    required: false
  username:
    type: string
    description: "Optional override of the username in <connection> (example: username@domain.tld) (required if <connection> is not specified)."
    required: false
  password:
    type: string
    description: "Optional override of the password in <connection>. (required if <connection> is not specified)"
    required: false
    secret: true
  location_id:
    type: number
    required: false
    description: "Scope by locations"
  organization_id:
    type: number
    required: false
    description: "Scope by organizations"
  id:
    type: string
    required: true
  config_group:
    type: object
    required: true
    description: >
       "description: 
        parameters:
            puppetclass_ids:
              required: false
              type: array
              description: ''
            name:
              required: false
              type: string
              description: ''
            "