---
description: "Update a provisioning template (resource: PUT /api/config_templates/:id)"
enabled: true
runner_type: "python-script"
entry_point: lib/action.py
name: config_templates.update
pack: foreman
parameters:
  operation:
    type: string
    default: config_templates.update
    immutable: true
  connection:
    type: string
    description: "Name of <connection> from this pack's configuration that specifies how to connect to a server."
    required: false
  server:
    type: string
    description: "Optional override of the server in <connection> (required if <connection> is not specified)."
    required: false
  username:
    type: string
    description: "Optional override of the username in <connection> (example: username@domain.tld) (required if <connection> is not specified)."
    required: false
  password:
    type: string
    description: "Optional override of the password in <connection>. (required if <connection> is not specified)"
    required: false
    secret: true
  location_id:
    type: number
    required: false
    description: "Scope by locations"
  organization_id:
    type: number
    required: false
    description: "Scope by organizations"
  id:
    type: string
    required: true
  config_template:
    type: object
    required: true
    description: >
       "description: 
        parameters:
            operatingsystem_ids:
              required: false
              type: array
              description: Array of operating system IDs to associate with the template
            template_combinations_attributes:
              required: false
              type: array
              description: Array of template combinations (hostgroup_id, environment_id)
            locked:
              required: false
              type: boolean
              description: Whether or not the template is locked for editing
            name:
              required: false
              type: string
              description: template name
            snippet:
              required: false
              type: boolean
              description: ''
            template_kind_id:
              required: false
              type: number
              description: not relevant for snippet
            template:
              required: false
              type: string
              description: ''
            audit_comment:
              required: false
              type: string
              description: ''
            location_ids:
              required: false
              type: array
              description: REPLACE locations with given ids
            organization_ids:
              required: false
              type: array
              description: REPLACE organizations with given ids.
            "